# Generated by Django 3.1 on 2022-05-24 07:48
from internproject.models.HomeBanner import upload_banner_img
from internproject.models.HomeCards import upload_card_img
from django.db import migrations, models
import internproject.models.HomeBanner
import internproject.models.HomeCards


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to=upload_card_img)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to=upload_banner_img)),
            ],
        ),
    ]
